import "@/app/globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

import { StoreProvider } from "@/app/providers/storeProvider";

const myFont = localFont({
  src: "../public/fonts/yekan/Yekan.ttf",
});

export const metadata: Metadata = {
  title: "فروشگاه اینترنتی آوا",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={myFont.className}>
       <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
